// Code generated by "stringer -type=Currency"; DO NOT EDIT.

package currency

import "fmt"

const _Currency_name = "BTCETHLTCPPCZEC"

var _Currency_index = [...]uint8{0, 3, 6, 9, 12, 15}

func (i Currency) String() string {
	if i < 0 || i >= Currency(len(_Currency_index)-1) {
		return fmt.Sprintf("Currency(%d)", i)
	}
	return _Currency_name[_Currency_index[i]:_Currency_index[i+1]]
}
